Updating manifest and adding WebScience
mozilla-rally/study-template pull request #94
Opened 2021-04-06 01:18 UTC by jonathanmayer

Resolves #86 and #87.

2021-05-13 17:50 UTC, rhelmer requested changes
Could you please rebase this to fix the integration test failure also? Thanks!

2021-05-13 17:50 UTC, rhelmer commented on src/background.js
> +import * as webScience from "@mozilla/web-science";
@jonathanmayer this causes a lint failure:
`error  'webScience' is defined but never used  no-unused-vars`

Can you make it do something more interesting?

2021-05-27 03:26 UTC, rhelmer approved these changes
This lgtm and is an improvement over what we have now, thanks!

2021-05-27 04:24 UTC, jonathanmayer commented
Looks like you'll have to do the merge, I don't have write privileges in this repo.

2021-05-28 18:36 UTC, merged